### PR TITLE
Update to 20160719

### LINKED ISSUE #1: Update to 20160205
Nice package, and chance of an update to the "msys2-x86_64-20160205.exe" version?

### PR DESCRIPTION
**Pull request by petemounce**
Fixes #1.

Added myself to authors.

I've tested x64 myself, but I don't have an x86 box to try out. I believe that chocolatey moderation automation does that now.

### CODE REVIEW

**Review by userzimmermann — APPROVED** [review]
Everything fine again... almost ;) `<authors>` is used for the original software developers. I will move you to `<owners>` later...

**Review by userzimmermann — APPROVED** [review]
Also thanks for update of **CHANGES.md**

**Comment by userzimmermann** [comment]
Hi @petemounce again :) Thanks for the update! That package had got so unusable... ;( I will merge this now and then move it to the **msys2** branch. Please open further **msys2** package PRs against that branch.

**Comment by userzimmermann** [comment]
@petemounce I will also add you to the Copyright. If you don't complain ;)

**Comment by petemounce** [comment]
That's fine. Thanks for review and merge!

**Pull request merged**
